%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: \\sunrga.stb.sun.ac.za\home\let\18283217\Downloads\Space+Missions\space_missions.csv
%
% Auto-generated by MATLAB on 31-Mar-2026 02:56:10

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Company", "Location", "Date", "Time", "Rocket", "Mission", "RocketStatus", "Price", "MissionStatus"];
opts.VariableTypes = ["categorical", "categorical", "datetime", "datetime", "categorical", "string", "categorical", "string", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Mission", "Price"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Company", "Location", "Rocket", "Mission", "RocketStatus", "Price", "MissionStatus"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Date", "InputFormat", "yyyy-MM-dd", "DatetimeFormat", "preserveinput");
opts = setvaropts(opts, "Time", "InputFormat", "HH:mm:ss", "DatetimeFormat", "preserveinput");

% Import the data
spacemissions = readtable("\\sunrga.stb.sun.ac.za\home\let\18283217\Downloads\Space+Missions\space_missions.csv", opts);


%% Clear temporary variables
clear opts

% Preview
head(spacemissions)
summary(spacemissions)

%% Data Cleaning

%Handle missing values

% Check missing values
missingCounts = sum(ismissing(spacemissions));

% Remove rows with missing mission status (critical field)
data = rmmissing(spacemissions, 'DataVariables', {'MissionStatus'});

% Convert Date column

data.Date = datetime(data.Date, 'InputFormat', 'yyyy-MM-dd');

% Extract Year
data.Year = year(data.Date);

% Clean Price column

%Convert Price from string → numeric
data.Price = strrep(data.Price, '$', ''); %Remove $ signs (if present)
data.Price = str2double(data.Price);% Convert to numeric

%Handle missing values
medianPrice = median(data.Price, 'omitnan');
data.Price = fillmissing(data.Price, 'constant', medianPrice);

%% Exploratory Data Analysis (EDA)

% Rocket launches trend over time

% 1. Summarize the data
launchesPerYear = groupsummary(data, 'Year');

% 2. Visualization
figure;
plot(launchesPerYear.Year, launchesPerYear.GroupCount, '-o', 'LineWidth', 2);
title('Rocket Launches Over Time');
xlabel('Year');
ylabel('Number of Launches');
grid on;

% Mission Success Rate Over Time

% 1. Ensuring MissionStatus is treated as a string array
status = string(data.MissionStatus);

% 2. Creating the Success column (Logical 1 for Success, 0 for everything else)
data.Success = (status == "Success");

% 3. Run summary
successRate = groupsummary(data, 'Year', 'mean', 'Success');

% 4. Plot
figure;
plot(successRate.Year, successRate.mean_Success, '-o');
title('Mission Success Rate Over Time');
grid on;

%% Countries with most successful missions

% Extract country from Location

% 1. Convert to string array
locStrings = string(data.Location);

% 2. Use a cellfun to grab the last piece of every row individually
% This handles rows with 0, 1, 2, or 10 commas perfectly
splitCells = cellfun(@(x) strsplit(x, ','), locStrings, 'UniformOutput', false);
data.Country = strtrim(cellfun(@(x) x{end}, splitCells, 'UniformOutput', false));


% Count successes by country

% 1. Filter for successes
successData = data(data.Success == 1, :);

% 2. Group by Country 
countrySuccess = groupsummary(successData, 'Country');

% 3. Sort descending so the highest count is at the top
countrySuccess = sortrows(countrySuccess, 'GroupCount', 'descend');

% 4. Take the top 10
top10 = countrySuccess(1:min(10, height(countrySuccess)), :);

% 5. Plotting
figure;
barh(top10.Country, top10.GroupCount);
set(gca, 'YDir', 'reverse'); % This puts the #1 country at the top of the chart
title('Top 10 Countries by Successful Missions');
xlabel('Number of Successes');
ylabel('Country');
grid on;

%% Most used rocket

% Fix: Remove 'count'
rocketUsage = groupsummary(data, 'Rocket');

% The rest of your logic is perfect
rocketUsage = sortrows(rocketUsage, 'GroupCount', 'descend');
topRocket = rocketUsage(1:10, :);

figure;
barh(topRocket.Rocket, topRocket.GroupCount);
set(gca, 'YDir', 'reverse'); % Keep the most used at the top
title('Most Used Rockets');
xlabel('Launch Count');
ylabel('Rocket Type');
grid on;


% 1. Group by Rocket name and count launches

rocketUsage = groupsummary(data, 'Rocket');

% 2. Sort the table by GroupCount (descending)
rocketUsage = sortrows(rocketUsage, 'GroupCount', 'descend');

% 3. Extract the Top 10
top10Rockets = rocketUsage(1:10, :);

% 4. Visualization (Horizontal Bar Chart)
figure;
% Convert categorical/string names to string array for the plot labels
barh(string(top10Rockets.Rocket), top10Rockets.GroupCount);

% Formatting
set(gca, 'YDir', 'reverse'); % Puts the #1 rocket at the top
title('Top 10 Most Used Rockets');
xlabel('Total Number of Launches');
ylabel('Rocket Model');
grid on;

% Optional: Display the results in the command window
disp('Top 10 Most Used Rockets:');
disp(top10Rockets);


% Check if top rocket is active

% 1. Get the name of the top rocket
topRocketName = string(topRocket.Rocket(1)); 

% 2. Find all rows where the rocket name contains our target

matches = contains(string(data.Rocket), topRocketName, 'IgnoreCase', true);
statusInfo = data(matches, {'Rocket', 'RocketStatus'});

% 3. Display the unique status
unique(statusInfo)

%% Launch location patterns

% Fix: Remove the 'count' string
locationCounts = groupsummary(data, 'Location');

% This part is already perfect
locationCounts = sortrows(locationCounts, 'GroupCount', 'descend');
topLocations = locationCounts(1:10, :);

figure;
barh(topLocations.Location, topLocations.GroupCount);
set(gca, 'YDir', 'reverse'); % Puts the #1 spot at the top
title('Top Launch Locations');
xlabel('Number of Launches');



% 1. Group by Location and count launches
% (Leaving out 'count' to avoid the syntax error in your version)
locationUsage = groupsummary(data, 'Location');

% 2. Sort by GroupCount in descending order
locationUsage = sortrows(locationUsage, 'GroupCount', 'descend');

% 3. Extract the Top 10
top10Locations = locationUsage(1:10, :);

% 4. Visualization (Horizontal Bar Chart)
figure;
% Convert categorical/string to string array for the labels
barh(string(top10Locations.Location), top10Locations.GroupCount);

% Formatting
set(gca, 'YDir', 'reverse'); % Put the #1 location at the top
title('Top 10 Launch Locations Globally');
xlabel('Total Number of Launches');
ylabel('Launch Site');
grid on;

% Optional: Display the list in the Command Window
disp('Top 10 Launch Locations:');
disp(top10Locations);



%% Cost vs Success

figure;
scatter(data.Price, data.Success);
title('Price vs Mission Success');
xlabel('Cost (Millions USD)');
ylabel('Success (1 = Yes)');


%% Active vs Inactive rockets

% 1. Get the summary
rocketStatusCount = groupsummary(data, 'RocketStatus');

% 2. Reset and create the explode vector based on CURRENT table height
% This prevents the "X and EXPLODE must be the same length" error
explode = zeros(height(rocketStatusCount), 1);
activeIdx = strcmpi(string(rocketStatusCount.RocketStatus), 'StatusActive');
explode(activeIdx) = 1;

% 3. Plot with the explicit label conversion
figure;
pie(double(rocketStatusCount.GroupCount), explode, cellstr(rocketStatusCount.RocketStatus));

title('Active vs Inactive Rockets');
legend('Location', 'bestoutside');

